apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: frontend-ingress
    namespace: dupontdoku-staging
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
    ingressClassName: nginx
    tls:
        -   hosts:
                - staging.dupontarchive.mov
            secretName: frontend-tls
    rules:
        -   host: staging.dupontarchive.mov
            http:
                paths:
                    -   backend:
                            service:
                                name: frontend-service
                                port:
                                    number: 80
                        path: /
                        pathType: Prefix
